server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(bxjPmOguMVVznoKSvGExB0wIRPeCY6baF6gsacebXkrslN7YAE9nqrBnEkdh8NguhUIsVp1BRJnIyoaReGd34VLYio6F45ZRgq/515oewpugGD2NUS6u6WOfMKSapEkTAgwwTZLePNM=)
    username: ENC(Myd7XFw0EYm4aSHuUARop6tlAOAgfYr7VU1R9L/BVA4=)
    password: ENC(nAuLHBNgLeMl/P7ZIqfd1jZxlIyUGa1ctxpo0nwWmFo=)

  data:
    mongodb:
      host: localhost
      port: 27017
      database: web-chat
      log:
        query:
          enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.webchat

jwt:
  secret: asdd!#241asdasD@^2345sdfaDA^@sdfas^@#$@#asfas13$@#$!asfhsdfsd@#$#@$*34ggb45@%%#

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG