server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(EevH82O2TDufzfy/8y71TI2oYK7NHICqsF19CdM+0L2zuPMrW4hXtcHePI6sIC3fj1X3FF0JOqW3F5wol0FWj1NyJvaMlRLwVtVTgmhg2Au0ct+/aFQ+X3IvWayxVrKi7u5jZf0H1qWJybQS33+8aw==)
    username: ENC(Myd7XFw0EYm4aSHuUARop6tlAOAgfYr7VU1R9L/BVA4=)
    password: ENC(nAuLHBNgLeMl/P7ZIqfd1jZxlIyUGa1ctxpo0nwWmFo=)

  data:
    mongodb:
      host: localhost
      port: 27017
      database: web-chat
      authentication-database: admin
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
      log:
        query:
          enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.webchat

jwt:
  secret: asdd!#241asdasD@^2345sdfaDA^@sdfas^@#$@#asfas13$@#$!asfhsdfsd@#$#@$*34ggb45@%%#

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: info
      connection: OFF
      sqlonly: info
      sqltiming: OFF

