version: '3.8'

services:
  mongodb:
    image: mongo:6.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

volumes:
  mongodb_data:
